[project]
name = 'Space-Debris-Tracking-and-Removal-Incentive-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.space-debris-token]
path = 'contracts/space-debris-token.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
